### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by ShadabFaiz** [CuppaLabs/angular2-multiselect-dropdown#358]
After installing it, i'm getting version mismatch error:

``` node
ERROR in Error: Metadata version mismatch for module /home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/angular2-multiselect-dropdown/angular2-multiselect-dropdown.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/Faiz/GitRepos/Goatry/goatry_admin/src/app/app.module.ts, resolving symbol AppModule in /home/Faiz/GitRepos/Goatry/goatry_admin/src/app/app.module.ts
    at syntaxError (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/Faiz/GitRepos/Goatry/goatry_admin/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

webpack: Failed to compile.
```
Using version: 4.2.1
Angular Version: 4.4.4
This problem does not exist when I ver 3.2.1

**Comment by ShadabFaiz** [comment]
Not sure why it happened but restarting my vscode fix this problem. weird

**Comment by maalexs** [comment]
I have the same problem. I think this happens because of tslib dependency that was added after version 4+. It requires higher version of typescript than you have.

**Comment by seraries** [comment]
Hi @CuppaLabs ! Which version of typescript is required in order to not get this error. I'm running into the same problem with an Angular 4 app that is using the plugin. In order to use v 4.6.2 of the plugin I have to manually change the metadata file to version 3 from version 4 (I know it's bad to do). Will just updating Typescript be sufficient, or would we need to update our app to Angular 6 in order to properly work with the newer versions of this plugin?
