### ISSUE TITLE
angular 9 update?

### ISSUE THREAD

**Issue by abrahamsankutty** [CuppaLabs/angular2-multiselect-dropdown#475]
When can we expect angular 9 updates?

**Comment by dadosto** [comment]
Hi!

Is it possible that the following error originates from the angular-2-multiselect-dropdown component?
I tried to upgrade my project to Angular 9 and this error started showing up.

`ERROR in Error: Cannot assign value "$event" to template variable "data". Template variables are read-only.
    at _AstToIrVisitor.visitPropertyWrite (...node_modules\@angular\compiler\bundles\compiler.umd.js:8897:31)
    at PropertyWrite.visit (...node_modules\@angular\compiler\bundles\compiler.umd.js:7768:28)
    at convertActionBinding (...node_modules\@angular\compiler\bundles\compiler.umd.js:8498:49)
    at prepareEventListenerParameters (...node_modules\@angular\compiler\bundles\compiler.umd.js:17649:27)
    at Object.params (...node_modules\@angular\compiler\bundles\compiler.umd.js:18776:24)
    at ...node_modules\@angular\compiler\bundles\compiler.umd.js:18547:94
    at Array.map (<anonymous>)
    at ...node_modules\@angular\compiler\bundles\compiler.umd.js:18547:60
    at ...node_modules\@angular\compiler\bundles\compiler.umd.js:17806:87
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (...node_modules\@angular\compiler\bundles\compiler.umd.js:17806:60)
    at ...node_modules\@angular\compiler\bundles\compiler.umd.js:18348:60
    at ...node_modules\@angular\compiler\bundles\compiler.umd.js:17784:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (...node_modules\@angular\compiler\bundles\compiler.umd.js:17784:37)
    at Object.compileComponentFromMetadata (...node_modules\@angular\compiler\bundles\compiler.umd.js:19471:58)`

My first assumption was that the error is specific to my code, but i have no [data] binding, as stated in the error. In fact, the only [data] binding is coming from my usage of the angular-2-multiselect-dropdown.

Cheers!
