### ISSUE TITLE
using (scroll) on any other element causes Maximum call stack size exceeded

### ISSUE THREAD

**Issue by my-good-ideas** [CuppaLabs/angular2-multiselect-dropdown#601]
If I use (scroll) on any other element in the ui, where I also use angular2-multiselect-dropdown, I get following error:

core.js:6456 ERROR RangeError: Maximum call stack size exceeded
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:191:32)
    at SafeSubscriber.next (Subscriber.js:122:1)
    at Subscriber._next (Subscriber.js:72:1)
    at Subscriber.next (Subscriber.js:49:1)
    at EventEmitter_.next (Subject.js:39:1)
    at EventEmitter_.emit (core.js:25946:1)
    at ScrollDirective.onClick (angular2-multiselect-dropdown.js:1014:1)
    at ScrollDirective_scroll_HostBindingHandler (angular2-multiselect-dropdown.js:1019:97)
    at executeListenerWithErrorHandling (core.js:15285:1)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.js:15323:1)

Version 5.0.4
Angular 12.1
example use:
<div (scroll)="onScroll($event)"></div>

**Comment by amandalynn** [comment]
Same here. Have you found a way around it?
