### ISSUE TITLE
Angular 13 - Type AngularMultiSelectModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by manjeetyadv** [CuppaLabs/angular2-multiselect-dropdown#611]
I am getting this error in the console.

Angular version - 13
Package version - latest.

I have tried deleting node_modules and nothing seems working.

`Error: Uncaught (in promise): Error: Type AngularMultiSelectModule does not have 'ɵmod' property.
Error: Type AngularMultiSelectModule does not have 'ɵmod' property.
    at getNgModuleDef (core.mjs:1139:1)
    at recurse (core.mjs:21757:1)
    at recurse (core.mjs:21768:1)
    at recurse (core.mjs:21768:1)
    at recurse (core.mjs:21768:1)
    at registerNgModuleType (core.mjs:21753:1)
    at new NgModuleFactory (core.mjs:21875:1)
    at Compiler.compileModuleSync (core.mjs:25129:1)
    at Compiler.compileModuleAsync (core.mjs:25135:1)
    at router.mjs:3984:43
    at doInnerSub (mergeInternals.js:19:18)
    at outerNext (mergeInternals.js:14:1)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)
    at innerFrom.js:61:28
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25548:1)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25535:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25535:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)`

**Comment by jagdishkr** [comment]
are you this issue?

**Comment by jagdishkr** [comment]
I am also getting same issue in @12,
delete nodez_module and reinstall, once cleanse cache but not resolve
